### ISSUE TITLE
mercury-avx2@123.0.1: Decompress Error

### ISSUE THREAD

**Issue by PlatFlat** [loustact/locket#2]
Could not find 'mercury in C:\Users\Username\scoop\apps\mercury-avx2\123.0.1'! (error 16)

Zip file has no issue upon downloaded. I can manually decompress, but something in this new update might have broken something.

**Comment by loustact** [comment]
Sorry for the late response as I didn't noticed this issue. I'll check on it later when I have time.

**Comment by loustact** [comment]
Found spare time and fixed it! Seems the issue was just about what directory is scoop extracting to. So it's prettyt much an easy fix.
