### ISSUE TITLE
mercury-avx2@129.0.2: Decompress Error

### ISSUE THREAD

**Issue by PlatFlat** [loustact/locket#4]
Loading mercury_129.0.2_win64_AVX2.zip from cache.
Extracting mercury_129.0.2_win64_AVX2.zip ... ERROR Could not find 'mercury in C:\Users\example\scoop\apps\mercury-avx2\129.0.2\mercury_129.0.2_win64_AVX2'! (error 16)

ERROR This application failed to update: mercury-avx2

**Comment by loustact** [comment]
Should be fixed now
